config/routes.rb
Rails.application.routes.draw do
  resources :students do
    get 'suggest_team', to: 'students#suggest_team'
    post 'suggest_team', to: 'students#suggest_team'
  end


  resources :appraisals
  resources :appraisers
  resources :teams
  resources :courses

  root to: "roles#index"
  get 'set_student', to: 'roles#set_student'
  get 'set_student_with_new_appraisal', to: 'roles#set_student_with_new_appraisal'
  get 'set_appraiser', to: 'roles#set_appraiser'
  get 'mark_students_as_presented', to: 'teams#mark_students_as_presented'
  
end

app/models/appraisal.rb
class Appraisal < ApplicationRecord
  belongs_to :team
  belongs_to :appraiser

  validate :appraisal_amount
  validate :has_already_voted, if: :appraiser_present?

  validates_presence_of :working_software, :process, :pitch, :inovation, :team_formation

  def mark_students_with_new_appraisal
    team.students.each do |student|
      student.update(new_appraisal: true)
    end
  end

  private

  def appraiser_present?
    appraiser.present?
  end

  def appraisal_amount
    [:working_software, :process, :pitch, :inovation, :team_formation].each do |attribute_to_validate|
      if send(attribute_to_validate).present?
        if send(attribute_to_validate).to_i < 0 or send(attribute_to_validate).to_i > 5
          errors.add(attribute_to_validate, "has invalid amount!")
        end
      end
    end
  end

  def has_already_voted
    if appraiser.appraisals.map(&:team).include?(team)
      errors.add(:appraiser, "has already voted on current team!")
    end
  end
end

app/controllers/appraisals_controller.rb
class AppraisalsController < ApplicationController
  before_action :set_appraisal, only: [:show, :edit, :update, :destroy]

  # GET /appraisals
  # GET /appraisals.json
  def index
    @appraisals = Appraisal.all
  end

  # GET /appraisals/1
  # GET /appraisals/1.json
  def show
  end

  # GET /appraisals/new
  def new
    if Team.all_appraised?
      redirect_to appraisals_url, alert: "Times já foram avaliados por todos avaliadores"
    end

    @appraisal = Appraisal.new
  end

  # GET /appraisals/1/edit
  def edit
  end

  # POST /appraisals
  # POST /appraisals.json
  def create
    @appraisal = Appraisal.new(appraisal_params)

    respond_to do |format|
      if @appraisal.save
        @appraisal.mark_students_with_new_appraisal

        format.html { redirect_to @appraisal, notice: 'Appraisal was successfully created.' }
        format.json { render :show, status: :created, location: @appraisal }
      else
        format.html { render :new }
        format.json { render json: @appraisal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appraisals/1
  # PATCH/PUT /appraisals/1.json
  def update
    respond_to do |format|
      if @appraisal.update(appraisal_params)
        format.html { redirect_to @appraisal, notice: 'Appraisal was successfully updated.' }
        format.json { render :show, status: :ok, location: @appraisal }
      else
        format.html { render :edit }
        format.json { render json: @appraisal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appraisals/1
  # DELETE /appraisals/1.json
  def destroy
    @appraisal.destroy
    respond_to do |format|
      format.html { redirect_to appraisals_url, notice: 'Appraisal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appraisal
      @appraisal = Appraisal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appraisal_params
      params.require(:appraisal).permit(:name, :team_id, :appraiser_id, :working_software, :process, :pitch, :inovation, :team_formation)
    end
end

app/views/appraisals/_form.html.erb
<%= form_with(model: appraisal, local: true) do |form| %>
  <% if appraisal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appraisal.errors.count, "error") %> prohibited this appraisal from being saved:</h2>

      <ul>
      <% appraisal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.collection_select :team_id, Team.all, :id, :name, {:include_blank => true} %>
  </div>

  <div class="field">
    <%= form.label :appraiser_id %>
    <%= form.collection_select :appraiser_id, Appraiser.all, :id, :name, {:include_blank => true} %>
  </div>

  <div class="field">
    <%= form.label :working_software %>
    <%= form.number_field :working_software %>
  </div>

  <div class="field">
    <%= form.label :process %>
    <%= form.number_field :process %>
  </div>

  <div class="field">
    <%= form.label :pitch %>
    <%= form.number_field :pitch %>
  </div>

  <div class="field">
    <%= form.label :inovation %>
    <%= form.number_field :inovation %>
  </div>

  <div class="field">
    <%= form.label :team_formation %>
    <%= form.number_field :team_formation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appraisals/edit.html.erb
<h1>Editar Avaliação</h1>

<%= render 'form', appraisal: @appraisal %>

<%= link_to 'Show', @appraisal %> |
<%= link_to 'Back', appraisals_path %>

app/views/appraisals/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1>Avaliações</h1>

<table class="table">
  <thead>
    <tr>
      <th>Time</th>
      <th>Avaliador</th>
      <th>Software Funcionando</th>
      <th>Processo</th>
      <th>Pitch</th>
      <th>Inovação</th>
      <th>Formação do Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appraisals.each do |appraisal| %>
      <tr>
        <td><%= appraisal.team.name %></td>
        <td><%= appraisal.appraiser.name %></td>
        <td><%= appraisal.working_software %></td>
        <td><%= appraisal.process %></td>
        <td><%= appraisal.pitch %></td>
        <td><%= appraisal.inovation %></td>
        <td><%= appraisal.team_formation %></td>
        <td><%= link_to 'Show', appraisal %></td>
        <td><%= link_to 'Edit', edit_appraisal_path(appraisal) %></td>
        <td><%= link_to 'Destroy', appraisal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Avaliação', new_appraisal_path %>

app/views/appraisals/new.html.erb
<h1>Nova Avaliação</h1>

<%= render 'form', appraisal: @appraisal %>

<%= link_to 'Back', appraisals_path %>

app/views/appraisals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @appraisal.team.name %>
</p>

<p>
  <strong>Avaliador:</strong>
  <%= @appraisal.appraiser.name %>
</p>

<p>
  <strong>Software Funcionando:</strong>
  <%= @appraisal.working_software %>
</p>

<p>
  <strong>Processo:</strong>
  <%= @appraisal.process %>
</p>

<p>
  <strong>Pitch:</strong>
  <%= @appraisal.pitch %>
</p>

<p>
  <strong>Inovação:</strong>
  <%= @appraisal.inovation %>
</p>

<p>
  <strong>Time formation:</strong>
  <%= @appraisal.team_formation %>
</p>

<%= link_to 'Edit', edit_appraisal_path(@appraisal) %> |
<%= link_to 'Back', appraisals_path %>