config/routes.rb
Rails.application.routes.draw do
  resources :students do
    get 'suggest_team', to: 'students#suggest_team'
    post 'suggest_team', to: 'students#suggest_team'
  end


  resources :appraisals
  resources :appraisers
  resources :teams
  resources :courses

  root to: "roles#index"
  get 'set_student', to: 'roles#set_student'
  get 'set_student_with_new_appraisal', to: 'roles#set_student_with_new_appraisal'
  get 'set_appraiser', to: 'roles#set_appraiser'
  get 'mark_students_as_presented', to: 'teams#mark_students_as_presented'
  
end

app/models/appraiser.rb
class Appraiser < ApplicationRecord
  has_many :appraisals

  validates_presence_of :name
end

app/controllers/appraisers_controller.rb
class AppraisersController < ApplicationController
  before_action :set_appraiser, only: [:show, :edit, :update, :destroy]

  # GET /appraisers
  # GET /appraisers.json
  def index
    @appraisers = Appraiser.all
  end

  # GET /appraisers/1
  # GET /appraisers/1.json
  def show
  end

  # GET /appraisers/new
  def new
    @appraiser = Appraiser.new
  end

  # GET /appraisers/1/edit
  def edit
  end

  # POST /appraisers
  # POST /appraisers.json
  def create
    @appraiser = Appraiser.new(appraiser_params)

    respond_to do |format|
      if @appraiser.save
        format.html { redirect_to @appraiser, notice: 'Appraiser was successfully created.' }
        format.json { render :show, status: :created, location: @appraiser }
      else
        format.html { render :new }
        format.json { render json: @appraiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appraisers/1
  # PATCH/PUT /appraisers/1.json
  def update
    respond_to do |format|
      if @appraiser.update(appraiser_params)
        format.html { redirect_to @appraiser, notice: 'Appraiser was successfully updated.' }
        format.json { render :show, status: :ok, location: @appraiser }
      else
        format.html { render :edit }
        format.json { render json: @appraiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appraisers/1
  # DELETE /appraisers/1.json
  def destroy
    @appraiser.destroy
    respond_to do |format|
      format.html { redirect_to appraisers_url, notice: 'Appraiser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appraiser
      @appraiser = Appraiser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appraiser_params
      params.require(:appraiser).permit(:name)
    end
end

app/views/appraisers/_form.html.erb
<%= form_with(model: appraiser, local: true) do |form| %>
  <% if appraiser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appraiser.errors.count, "error") %> prohibited this appraiser from being saved:</h2>

      <ul>
      <% appraiser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appraisers/edit.html.erb
<h1>Editar Avaliador</h1>

<%= render 'form', appraiser: @appraiser %>

<%= link_to 'Show', @appraiser %> |
<%= link_to 'Back', appraisers_path %>

app/views/appraisers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Avaliadores</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Times Avaliados</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appraisers.each do |appraiser| %>
      <tr>
        <td><%= appraiser.name %></td>
        <td><%= appraiser.appraisals.map{|appraisal| appraisal.team.name }.join(", ") %></td>
        <td><%= link_to 'Show', appraiser %></td>
        <td><%= link_to 'Edit', edit_appraiser_path(appraiser) %></td>
        <td><%= link_to 'Destroy', appraiser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Avaliador', new_appraiser_path %>

app/views/appraisers/new.html.erb
<h1>Novo Avaliador</h1>

<%= render 'form', appraiser: @appraiser %>

<%= link_to 'Back', appraisers_path %>

app/views/appraisers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appraiser.name %>
</p>

<%= link_to 'Edit', edit_appraiser_path(@appraiser) %> |
<%= link_to 'Back', appraisers_path %>